---
- name: zabbix_agent
  hosts: zabbix_agent
  become: yes
  become_user: root
  vars_files:
    - "group_vars/zabbix_vars_agent2.yml"
    - "group_vars/zabbix_vars_agentd1.yml"
  roles:
    - role: zabbix_agent
