---
  - name: Remove zabbix-agent and/or zabbix-agent2 package
    apt:
      name: "{{item}}"
      state: absent
    with_items:
      - "zabbix-agent"
      - "zabbix-agent2"


  - name: Update all packages
    apt:
      update_cache: yes


  #só ativar esse passo se eu estiver subindo uma máquina nova
  #- name: Update all packages to their latest version
  #  apt:
  #    name: "*"
  #    state: latest


  - name: Install a list of packages
    apt:
      pkg:
      - net-tools
      - glances
      - htop
      - tcpdump  


  - name: Dowload and install library zabbix 5.4 when Ubuntu version is equal version 20.04
    apt:
      deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "20"


  - name: Dowload and install library zabbix 5.4 when Ubuntu version is equal version 18.04
    apt:
      deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"


  - name: Apt-get update -y
    apt:
      update_cache: yes


  - name: Install zabbix-agent2 package when Ubuntu version is equal version 20.04
    apt:
      pkg:
      - zabbix-agent2
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "20"


  - name: Install zabbix-agent2 package when Ubuntu version is equal version 18.04
    apt:
      pkg:
      - zabbix-agent
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"


  - name: Remove useless packages from the cache
    apt:
      autoclean: yes


  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes


  - name: Create config for zabbix_agentd
    template:
      src: zabbix_agentd.conf.j2
      dest: "/etc/zabbix/zabbix_agentd.conf"
      owner: root
      group: root
      mode: "0644"
    become_user: root
    become: true
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"


  - name: Create config for zabbix_agent2
    template:
      src: zabbix_agent2.conf.j2
      dest: "/etc/zabbix/zabbix_agent2.conf"
      owner: root
      group: root
      mode: "0644"
    become_user: root
    become: true
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "20"


  - name: checking the sudoers file
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%zabbix ALL=(ALL)'
      line: 'zabbix ALL=(ALL) NOPASSWD: ALL'
      #validate: 'visudo -c'
  

  - name: start zabbix-agent
    ansible.builtin.service:
      name: zabbix-agent2.service
      state: started
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "20"


  - name: Enable zabbix-agent
    ansible.builtin.service:
      name: zabbix-agent2.service
      enabled: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "20"


  - name: start zabbix-agent
    ansible.builtin.service:
      name: zabbix-agent.service
      state: started
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"


  - name: Enable zabbix-agent
    ansible.builtin.service:
      name: zabbix-agent.service
      enabled: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"

  



      

  




  
    

    
